# Generated by Django 6.0.1 on 2026-02-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.TextField(help_text='Comma separated')),
                ('frameworks', models.TextField(help_text='Comma separated')),
                ('databases', models.TextField(help_text='Comma separated')),
                ('tools', models.TextField(help_text='Comma separated')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
