# Generated by Django 6.0.1 on 2026-03-14 07:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fix_project_image_cloudinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassets',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo'),
        ),
        migrations.AlterField(
            model_name='profileassets',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resume'),
        ),
    ]
