# Generated by Django 6.0.1 on 2026-06-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_switch_profileassets_to_cloudinary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('installation_command', models.CharField(blank=True, help_text='e.g. pip install my-package', max_length=200)),
                ('pypi_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('tech_stack', models.CharField(blank=True, help_text='Comma separated tech/libraries used', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
