# Generated by Django 6.0.1 on 2026-06-19 06:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_skillcategory_alter_skill_skill_type_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Certificate badge or logo', max_length=255, null=True, verbose_name='image'),
        ),
    ]
